alias: "chromecast paused/stopped"
trigger:
  - platform: state
    entity_id: media_player.ratoncast
    from: 'playing'
condition:
  - condition: state
    entity_id: input_select.current_mode
    state: Soir
action:
  service: light.turn_on
  entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
  data:
    brightness: 90
