alias: "Kodi paused/stopped"
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.kodi
    from: 'playing'
condition:
  - condition: state
    entity_id: input_select.current_mode
    state: Film
  - condition: template
    value_template: '{{ states.media_player.kodi.media_content_type != "video" }}'
action:
  service: light.turn_on
  entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
  data:
    brightness: 90
