# dimming of light when playing media
- alias: "Kodi paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_select.current_mode
      state: Soir
    - condition: template
      value_template: '{{ states.media_player.kodi.media_content_type != "video" }}'
  action:
    service: light.turn_on
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
    data:
      brightness: 90

- alias: "Kodi playing"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_select.current_mode
      state: Soir
    - condition: template
      value_template: '{{ states.media_player.kodi.media_content_type != "video" }}'
  action:
    service: light.turn_on
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
    data:
      brightness: 30

- alias: "chromecast paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.ratoncast
      from: 'playing'
  condition:
    - condition: state
      entity_id: input_select.current_mode
      state: Soir
  action:
    service: light.turn_on
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
    data:
      brightness: 90

- alias: "chromecast playing"
  trigger:
    - platform: state
      entity_id: media_player.ratoncast
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_select.current_mode
      state: Soir
  action:
    service: light.turn_on
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
    data:
      brightness: 30
