# day time turn off the lights
- alias: Jour
  trigger:
    - platform: state
      entity_id: input_select.current_mode
      state: "Jour"
  action:
    service: light.turn_off

# evening normal turn on living room light, will have media playing dimming
- alias: Soir
  trigger:
    - platform: state
      entity_id: input_select.current_mode
      state: "Soir"
  action:
    service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      brightness: 90

# evening, turn on living room light, will disable media playing dimming
- alias: Soiree
  trigger:
    - platform: state
      entity_id: input_select.current_mode
      state: "Soiree"
  action:
    service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      brightness: 90

# night mode, very low ligthing in living room
- alias: Nuit
  trigger:
    - platform: state
      entity_id: input_select.current_mode
      state: "Nuit"
  action:
    service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      brightness: 10

# unused for now
- alias: Absent
  trigger:
    - platform: state
      entity_id: input_select.current_mode
      state: "Absent"
  action:
    service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      brightness: 10


