# triggers to change mode based on time
- alias: "night time"
  trigger:
    - platform: time
      hours: 1
      minutes: 30
      seconds: 0
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.current_mode
      option: "Nuit"
    
- alias: "day time"
  trigger:
    - platform: sun
      event: sunrise
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.current_mode
      option: "Jour"

- alias: "evening time"
  trigger:
    - platform: sun
      event: sunset
      offset: "-02:30:00"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.current_mode
      option: "Soir"
