alias: Jour
hide_entity: True
trigger:
  - platform: state
    entity_id: input_select.current_mode
    state: "Jour"
action:
  service: light.turn_off
  data:
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
