alias: Nuit
hide_entity: True
trigger:
  - platform: state
    entity_id: input_select.current_mode
    state: "Nuit"
action:
  service: light.turn_on
  data:
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3_0
    brightness: 10
