homeassistant:
  name: Famille des Ratons
  latitude: 48.80569
  longitude: 2.130699
  unit_system: metric
  time_zone: Europe/Paris # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  customize:
    !include includes/customize.yaml

media_player:
  !include includes/media_player.yaml

zwave:
  !include includes/zwave.yaml

device_tracker:
  !include includes/device_tracker.yaml

input_select:
  !include includes/input_select.yaml

sensor:
  !include includes/sensors.yaml

automation: 
  !include includes/automation.yaml

#simply enable various components
discovery:
logbook:
frontend:
sun:
history:
updater:
