homeassistant:
  name: Famille des Ratons
  latitude: 48.80569
  longitude: 2.130699
  unit_system: metric
  time_zone: Europe/Paris # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  customize:
    !include includes/customize.yaml

# Prediction of weather
sensor:
   platform: yr

weblink:
  entities:
    - name: Torrents
      url: http://192.168.0.2:9091
      icon: mdi:download

media_player:
  platform: kodi
  host: http://192.168.0.12
  port: 80
  name: Kodi

zwave:
  usb_path: /dev/cuaU0
  config_path: /usr/local/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-freebsd-10.3-RELEASE-amd64.egg/config
  polling_interval: 60000

device_tracker:
  platform: nmap_tracker
  hosts: 192.168.0.1/24
  home_interval: 10
  track_new_devices: no

sensor 2:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

sensor 3:
  platform: transmission
  host: 192.168.0.2
  port: 9091
  monitored_variables:
    - 'download_speed'
    - 'upload_speed'
    #- 'current_status'

input_select:
  current_mode:
    name: "Mode"
    options:
      - Jour
      - Soir
      - Soiree
      - Nuit
    initial: Jour
    icon: mdi:power-settings

automation: 
  !include includes/automation/modes_effect.yaml
  !include includes/automation/media_playing.yaml
  !include includes/automation/modes_trigger.yaml

#simply enable various components
discovery:
logbook:
frontend:
sun:
history:
updater:
