homeassistant:
  name: Famille des Ratons
  latitude: 48.80569
  longitude: 2.130699
  unit_system: metric
  time_zone: Europe/Paris # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  customize:
    !include includes/customize.yaml

discovery:

logbook:

frontend:

sun:

history:

updater:

# Prediction of weather
sensor:
   platform: yr

weblink:
  entities:
    - name: Torrents
      url: http://192.168.0.2:9091
      icon: mdi:download

media_player:
  platform: kodi
  host: http://192.168.0.12
  port: 80
  name: Kodi

zwave:
  usb_path: /dev/cuaU0
  config_path: /usr/local/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-freebsd-10.3-RELEASE-amd64.egg/config
  polling_interval: 60000

device_tracker:
  platform: nmap_tracker
  hosts: 192.168.0.1/24
  home_interval: 10
  track_new_devices: no

switch 1:
  platform: wake_on_lan
  mac_address: "bc:5f:f4:f0:98:9b"
  name: PC raton
  host: "192.168.0.13"

sensor 2:
  platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

sensor 3:
  platform: transmission
  host: 192.168.0.2
  port: 9091
  monitored_variables:
    - 'download_speed'
    - 'upload_speed'
    #- 'current_status'

input_select:
  current_mode:
    name: "Mode"
    options:
      - Jour
      - Soir
      - Soiree
      - Nuit
    initial: Jour
    icon: mdi:power-settings

automation: 
  !include includes/automation/modes.yaml
  - alias: "Kodi paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.kodi
        from: 'playing'
    condition:
      - condition: state
        entity_id: input_select.current_mode
        state: Soir
      - condition: template
        value_template: '{{ states.media_player.kodi.media_content_type != "video" }}'
    action:
      service: light.turn_on
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      data:
        brightness: 90

  - alias: "Kodi playing"
    trigger:
      - platform: state
        entity_id: media_player.kodi
        to: 'playing'
    condition:
      - condition: state
        entity_id: input_select.current_mode
        state: Soir
      - condition: template
        value_template: '{{ states.media_player.kodi.media_content_type != "video" }}'
    action:
      service: light.turn_on
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      data:
        brightness: 30

  - alias: "chromecast paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.ratoncast
        from: 'playing'
    condition:
      - condition: state
        entity_id: input_select.current_mode
        state: Soir
    action:
      service: light.turn_on
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      data:
        brightness: 90

  - alias: "chromecast playing"
    trigger:
      - platform: state
        entity_id: media_player.ratoncast
        to: 'playing'
    condition:
      - condition: state
        entity_id: input_select.current_mode
        state: Soir
    action:
      service: light.turn_on
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
      data:
        brightness: 30

  - alias: "night time"
    trigger:
      - platform: time
        hours: 1
        minutes: 30
        seconds: 0
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.current_mode
        option: "Nuit"
      
  - alias: "day time"
    trigger:
      - platform: sun
        event: sunrise
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.current_mode
        option: "Jour"

  - alias: "evening time"
    trigger:
      - platform: sun
        event: sunset
        offset: "-02:30:00"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.current_mode
        option: "Soir"
