- !include automation/kodi_stop.yaml
- !include automation/kodi_play.yaml
- !include automation/cast_stop.yaml
- !include automation/cast_play.yaml
- !include automation/switch_to_day.yaml
- !include automation/switch_to_evening.yaml
- !include automation/switch_to_movie.yaml
- !include automation/switch_to_night.yaml
- !include automation/time_night.yaml
- !include automation/time_day.yaml
- !include automation/time_evening.yaml
