# meteo
- platform: yr

# speedtest
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

# transmission torrent client status
- platform: transmission
  host: 192.168.0.2
  port: 9091
  monitored_variables:
    - 'download_speed'
    - 'upload_speed'

# OUTSIDE SENSOR
# temperature outside
- platform: mqtt
  state_topic: homie/bme-ext/temperature/degrees
  name: "Temperature Exterieure"
  qos: 0
  unit_of_measurement: "°C"
          
# humidity outside
- platform: mqtt
  state_topic: homie/bme-ext/humidity/relative
  name: "Humidite Exterieure"
  qos: 0
  unit_of_measurement: "%"

# pressure outside
- platform: mqtt
  state_topic: homie/bme-ext/pressure/pressure
  name: "Pression Exterieure"
  qos: 0
  unit_of_measurement: "hPa"

# battery outside
- platform: mqtt
  state_topic: homie/bme-ext/battery/battery
  name: "Batterie Exterieure"
  qos: 0
  unit_of_measurement: "V"
