# meteo
- platform: yr

# speedtest
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

# transmission torrent client status
- platform: transmission
  host: 192.168.0.2
  port: 9091
  monitored_variables:
    - 'download_speed'
    - 'upload_speed'

# temperature test
- platform: mqtt
  state_topic: devices/006500e0/temperature/degrees
  name: "Test temperature"
  qos: 0
  unit_of_measurement: "°C"
          
# humidity test
- platform: mqtt
  state_topic: devices/006500e0/humidity/relative
  name: "Test humidity"
  qos: 0
  unit_of_measurement: "%"

# pressure test
- platform: mqtt
  state_topic: devices/006500e0/pressure/pressure
  name: "Test pressure"
  qos: 0
  unit_of_measurement: "hPa"
